# Generated by Django 6.1 on 2026-08-30 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('genre', models.CharField(choices=[('FANTASY', 'Fantasía'), ('SCI_FI', 'Ciencia ficción'), ('MYSTERY', 'Misterio'), ('HORROR', 'Terror'), ('ROMANCE', 'Romance'), ('HISTORY', 'Historia'), ('BIOGRAPHY', 'Biografía'), ('SELF_HELP', 'Autoayuda'), ('TECHNOLOGY', 'Tecnología'), ('OTHER', 'Otro')], max_length=20)),
                ('author', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('publication_date', models.DateField()),
                ('pages', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('WANT_TO_READ', 'Por leer'), ('READING', 'Leyendo'), ('COMPLETED', 'Completado')], default='WANT_TO_READ', max_length=20)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('finished_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('title', 'author', 'user'), name='unique_book_per_user')],
            },
        ),
    ]
